FROM node:20-alpine

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps ./apps
COPY packages ./packages

#install dependencies
RUN npm install

# generate the client
RUN npm run db:generate

Run npm run build

CMD ["npm", "run", "start-user-app"]